### ISSUE TITLE
Updated examples to latest version Eve

### ISSUE THREAD

**Issue by koddr** [pyeve/eve-demo#17]
Hello, Nicola.

Will be nice to update examples to latest version 👍 

Because:

> Note. The demo is currently running v0.0.4 of the Eve framework. Eve-Demo is only updated when major Eve updates are released. Please refer to the official Eve repository for an up-to-date features list.

**Comment by nicolaiarocci** [comment]
Yup, what is probably needed is remove that note from the README. Demo repo is actually updated every once in a while, to match Eve releases. Will have to check and make sure that we are currently aligned. Thanks!
