### ISSUE TITLE
eve-demo requests are very very slow

### ISSUE THREAD

**Issue by pktippa** [pyeve/eve-demo#18]
Ran installing eve

```sh
$ pip install eve
```

Started Server

```sh
$ python run.py
```

When accessing the REST api's the response is very very slow, 

Environment details:

OS: Windows

Python: Python 3.6.3 :: Anaconda, Inc.

**Comment by nicolaiarocci** [comment]
So many things might be going wrong here. If you have a lot of data try setting `OPTIMIZE_PAGINATION_FOR_SPEED`: pagination impacts performance in a big way. And of course, make sure indexes are properly created and configured on mongo. Also, make your Mongo is responsive to the machine hosting your eve instance. Etc.
