### ISSUE TITLE
Live demo 500 error

### ISSUE THREAD

**Issue by pedro2555** [pyeve/eve-demo#19]
I've managed to break something I believe.

The live demo is returning a 500 on GET requests.

**Comment by nicolaiarocci** [comment]
It's fixed now. The problem was with a date which was changed to a value with a year prior to 1900, which is not supported by python's `strftime`

**Comment by pedro2555** [comment]
ok, thanks for reporting that. I wass really wonderingwhat happened.

Glad to know.

Do you think a check on this should be added, and return a bad request instead?

**Comment by nicolaiarocci** [comment]
There is an open ticket on the Eve repository abou this. Btw if you run your eve instance on Python 3.3+ it won't happen (should probably upgrade the eve demo instance)

**Comment by s-eswar** [comment]
> It's fixed now. The problem was with a date which was changed to a value with a year prior to 1900, which is not supported by python's `strftime`

@nicolaiarocci In attempt to attempt sample api using python eve, I get 500 error. How can it be fixed??
